export default data = [
  {
    "id": 1,
    "firma": "Firma X",
    "kalkisNoktasi": "İstanbul",
    "varisNoktasi": "Ankara",
    "tarih": "2023-07-26",
    "saat": "09:00",
    "biletFiyati": 450.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 2,
    "firma": "Firma X",
    "kalkisNoktasi": "İstanbul",
    "varisNoktasi": "Ankara",
    "tarih": "2023-07-26",
    "saat": "10:00",
    "biletFiyati": 450.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 3,
    "firma": "Firma X",
    "kalkisNoktasi": "İstanbul",
    "varisNoktasi": "Ankara",
    "tarih": "2023-07-26",
    "saat": "11:00",
    "biletFiyati": 450.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 4,
    "firma": "Firma Y",
    "kalkisNoktasi": "İstanbul",
    "varisNoktasi": "İzmir",
    "tarih": "2023-07-26",
    "saat": "09:00",
    "biletFiyati": 400.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 5,
    "firma": "Firma Y",
    "kalkisNoktasi": "İstanbul",
    "varisNoktasi": "İzmir",
    "tarih": "2023-07-26",
    "saat": "10:00",
    "biletFiyati": 400.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 6,
    "firma": "Firma X",
    "kalkisNoktasi": "Ankara",
    "varisNoktasi": "İstanbul",
    "tarih": "2023-07-28",
    "saat": "09:00",
    "biletFiyati": 475.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 16, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 7,
    "firma": "Firma X",
    "kalkisNoktasi": "Ankara",
    "varisNoktasi": "İstanbul",
    "tarih": "2023-07-28",
    "saat": "10:00",
    "biletFiyati": 450.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 8,
    "firma": "Firma X",
    "kalkisNoktasi": "Ankara",
    "varisNoktasi": "İstanbul",
    "tarih": "2023-07-28",
    "saat": "11:00",
    "biletFiyati": 450.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 9,
    "firma": "Firma Z",
    "kalkisNoktasi": "Ankara",
    "varisNoktasi": "İzmir",
    "tarih": "2023-07-28",
    "saat": "09:00",
    "biletFiyati": 350.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
  {
    "id": 10,
    "firma": "Firma Z",
    "kalkisNoktasi": "İzmir",
    "varisNoktasi": "Ankara",
    "tarih": "2023-07-28",
    "saat": "09:00",
    "biletFiyati": 350.0,
    "koltuklar": [
      { "numara": 1, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 2, "dolu": false },
      { "numara": 3, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 4, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 5, "dolu": false },
      { "numara": 6, "dolu": false },
      { "numara": 7, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 8, "dolu": false },
      { "numara": 9, "dolu": false },
      { "numara": 10, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 11, "dolu": false },
      { "numara": 12, "dolu": false },
      { "numara": 13, "dolu": false },
      { "numara": 14, "dolu": false },
      { "numara": 15, "dolu": false },
      { "numara": 16, "dolu": false },
      { "numara": 17, "dolu": false },
      { "numara": 18, "dolu": false },
      { "numara": 19, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 20, "dolu": false },
      { "numara": 21, "dolu": false },
      { "numara": 22, "dolu": true, "cinsiyet": "Kadın" },
      { "numara": 23, "dolu": false },
      { "numara": 24, "dolu": false },
      { "numara": 25, "dolu": false },
      { "numara": 26, "dolu": false },
      { "numara": 27, "dolu": false },
      { "numara": 28, "dolu": true, "cinsiyet": "Erkek" },
      { "numara": 29, "dolu": false },
      { "numara": 30, "dolu": true, "cinsiyet": "Erkek" }
    ]
  },
]